rm -r docs
mv build docs
cp docs/index.html docs/404.html
cp docs/index.html docs/menu.html
cp docs/index.html docs/menu-moment.html
cp docs/index.html docs/contact.html
cp docs/index.html docs/mentions-legales.html
cp docs/index.html docs/politique-confidentialite.html
cp docs/index.html docs/politique-cookies.html
git add .